Metrics/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
