Metrics/LineLength:
  Max: 130
Metrics/MethodLength:
  Max: 15
Style/Documentation:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
